baseURL: "https://nicolasnavarre.com/" 
title: Nicolas Santiago Navarre
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Tags
          url: tags/
          weight: 4 
        - name: Archive
          url: archive/
          weight: 5

params:
    description: "This website hosts Nicolas Navarre's research papers, course materials, data, curriculum vitae, and contact information."
    author: Nicolas Navarre
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["courses","papers", "tags"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Nicolas Navarre
          subtitle: "I am a PhD student at the University of Edinburgh in the Natural Language Processing CDT."
          imageUrl: "profile.jpeg"
          imageWidth: 300
          imageHeight: 250
          imageTitle: Nicolas Navarre
          buttons:
            - name: Papers
              url: papers/
            # - name: Data
            #   url: data/
            - name: Courses
              url: courses/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: CV
          url: NNavarre_CV_2025.pdf
        - name: Email
          url: mailto:nnavarre@ed.ac.uk
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=JkRcodQAAAAJ
        - name: GitHub
          url: https://github.com/navarrenicolas
        - name: LinkedIn
          url: https://www.linkedin.com/in/nnavarre/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Nicolas Navarre"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
